simplesocial/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
]

simplesocial/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
]

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html>
  <head>
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Star Social</title>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <!-- Latest compiled and minified CSS -->

<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->

<!--    &lt;!&ndash; Optional theme &ndash;&gt;-->
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">-->

<!--    &lt;!&ndash; Latest compiled and minified JavaScript &ndash;&gt;-->
<!--    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>-->


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar bg-primary navbar-dark">
        <div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                                  <li><a href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></li>
                                  <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                                  <li><a href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                                  <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
    						{% else %}
    						      <li><a href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></li>
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    						{% endif %}
    					</ul>

        </div>
    </nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>

    <footer class="footer">

		<div class="container">

			<div class="row">
				<div class="col-md-12 py-5">

					<div class="fa">
						<section class="Follow">
							<h1>Follow me on: </h1>
						</section>

						<a href="https://twitter.com/Morys0" target="_blank" rel="noopener noreferrer" class="tw-ic">
							<i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
						</a>
						<a href="https://www.linkedin.com/in/mourice-otieno-oduor-58188b166/" target="_blank" rel="noopener noreferrer" class="li-ic">
							<i class="fab fa-linkedin fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
						</a>
						<a href="https://www.instagram.com/mourice_otieno_moryso/" target="_blank" rel="noopener noreferrer" class="ins-ic">
							<i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
						</a>
						<a href="https://github.com/mourice-oduor" target="_blank" rel="noopener noreferrer" class="git-ic">
							<i class="fab fa-github fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
						</a>
					</div>
				</div>

		    </div>

	    </div>

		<div class="footer2">
			<footer>
				<p class="white"> Copyright &copy;2020. All Rights Reserved. </p>
				<p class="white"> Designed by @moryso |  <strong> Terms of Service  |</strong>
					<strong>Privacy Policy</strong>
				</p>
			</footer>
		</div>

	</footer>

    <canvas id="canvas"></canvas>



  </body>
  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>
</html>

simplesocial/templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Star Social!</h1>
    <h2>The best community for all things on outer space!</h2>

{% endblock %}

simplesocial/templates/test.html
{% extends "base.html" %}
{% block content %}

<h1>You are now logged in!</h1>

{% endblock %}

simplesocial/templates/thanks.html
{% extends "base.html" %}
{% block content %}

<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}